jenkinsmaster:
 image: yinglei/jenkinsci
 environment:
   JAVA_OPTS: "-Djava.awt.headless=true"
 volumes:
   - /var/jenkins_home
 ports:
   - "50000:50000"
   - "8080:8080"
 links:
   - db
db:
 image: mysql
 environment:
   MYSQL_ROOT_PASSWORD: petclinic
   MYSQL_DATABASE: petclinic
